---
title: 'BEX6510: Lasso and generalisations'
author: "Cameron Roach"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  ioslides_presentation: default
  beamer_presentation:
    toc: yes
  slidy_presentation: default
bibliography: library.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Introduction

Introduced by @Tibshirani1996-fg.

Allows for variable selection.

Good overviews in @James2014-xw, @Hastie2015-gy and @Friedman2001-vq.


## Motivation

Given $N$ samples $\left\{ (\mathbf{x}_i, y_i) \right\}_{i=1}^N$ where $\mathbf{x}_i = (x_{i1}, x_{i2}, \ldots, x_{ip})$ we wish to approximate the response $y_i \in \mathbb{R}$.

This can be done in using a standard OLS approach, but there are drawbacks:

* _Prediction accuracy_: low bias but large variance. Bias-variance tradeoff can improve prediction accuracy.
* _Interpretation_: difficult if $p$ is large.

## The lasso

The lasso combines the least-squares loss with an $L_1$ constraint,

$$
\min_{\beta_0, \boldsymbol{\beta}}  \left\{ 
  \frac{1}{2N} \sum^N_{i=1} \left(y_i -\beta_0 - \sum^p_{j=1} \beta_j x_{ij} \right)^2 +
  \lambda \sum^p_{j=1} \left| \beta_j \right|
\right\}.
$$

This can also be expressed in the Lagrangian form,

$$
\min_{\beta_0, \boldsymbol{\beta}}  \left\{ 
  \frac{1}{2N} \| \mathbf{y} - \mathbf{X}\boldsymbol{\beta} \|^2_2 + \lambda \| \mathbf{\beta} \|_1
\right\}.
$$

The factor $\frac{1}{2N}$ can be omitted, but does make $\lambda$ comparable for different sample sizes [@Hastie2015-gy].

## Ridge regression

Ridge regression predates the lasso and usese an $L2$ penalty instead of $L1$.

$$
\min_{\beta_0, \boldsymbol{\beta}}  \left\{ 
  \frac{1}{2N} \| \mathbf{y} - \mathbf{X}\boldsymbol{\beta} \|^2_2 + \lambda \| \mathbf{\beta} \|_2
\right\}.
$$

Interesting to compare the behaviour of ridge and lasso penalties on coefficients.

## Properties

* Lasso handles sparsity well (only a few non-zero columns).

__TODO: insert picture of parameter solution space and constraint regions.__

## Generalisations

### Elastic net

<!-- The lasso does not handle highly correlated variables well - unpredictable results in coefficient paths. -->

### Group lasso

### Fused lasso

## References {-}
